import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'
import { Web3Button } from '@web3modal/react'
import { useAccount, useBalance, useDisconnect } from 'wagmi'

export default function Home() {
  const [isWalletConnected, setIsWalletConnected] = useState(false)
  const { isConnected, address } = useAccount()
  const { disconnect } = useDisconnect()
  const { data, isError, isLoading } = useBalance({
    address: address,
  })

  useEffect(() => {
    setIsWalletConnected(isConnected)
  }, [isConnected])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Web3!</a>
        </h1>

        {isWalletConnected ? (
          <>
            <code>{address}</code>
            <button onClick={() => disconnect()}>Disconnect</button>
            <pre>{JSON.stringify(data, null, 2)}</pre>
          </>
        ): <Web3Button />}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
